### ISSUE TITLE
Import Orders Error "TypeError: sequence item 1: expected string or Unicode, NoneType found

### ISSUE THREAD

**Issue by shruti2018** [openlabs/magento_integration#187] opened 2014-02-02 13:14 UTC
The module Installed and tested connection OK, import sites and catalogs all OK, but when trying to import orders I got this error:

Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/magento_integration/wizard/import_orders.py", line 34, in import_orders
    cursor, user, store_view, context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/magento_integration/magento_.py", line 607, in import_orders_from_store_view
    order_api.info(order['increment_id']), new_context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/magento_integration/sale.py", line 179, in find_or_create_using_magento_data
    cursor, user, order_data, context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/magento_integration/sale.py", line 341, in create_using_magento_data
    context
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130922_231028-py2.7.egg/openerp/addons/magento_integration/partner.py", line 168, in create_using_magento_data
    [customer_data['firstname'], customer_data['lastname']]
TypeError: sequence item 0: expected string or Unicode, NoneType found

**Comment by shruti2018** [comment] 2014-02-02 13:40
please give me solution as soon as possible.....

**Comment by sharoonthomas** [comment] 2014-02-03 04:26
apparently the first name is empty.

**Comment by sharoonthomas** [comment] 2014-02-03 04:28
Duplicate of #105

**Closed as completed by sharoonthomas** 2014-02-03 04:28 UTC
