### ISSUE TITLE
maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by stevelicu** [openlabs/magento_integration#99] opened 2013-08-05 07:38 UTC
I followed instruction of the installation document but i get stuck when updating the module list

  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\pycountry__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\pycountry__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\pycountry__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\pycountry__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\pycountry__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 93, in find_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 169, in get_module_path
  File "ntpath.pyc", line 70, in join
RuntimeError: maximum recursion depth exceeded in cmp

**Comment by shalabhaggarwal** [comment] 2013-08-05 07:48
Ho @stevelicu 

If you check the first line of the stack trace, the file name is pycountry__init__.py. This seems wrong.

pycountry is not an openerp module and should not be present in addons. It is a python module which should be installed in python path. If it is some openerp module which has been renamed by you to pycountry then that is not supposed to be done.

Hope it helps!

**Comment by stevelicu** [comment] 2013-08-05 07:59
Ok when i first try to update the list i had the error no module named pycountry so i added the module in te addons directory, where do i have to place the pycountry module?

**Comment by shalabhaggarwal** [comment] 2013-08-05 08:02
This seems to be a duplicate of #91 .

**Comment by stevelicu** [comment] 2013-08-05 08:29
so bassicly this means this module doesn't work when running openerp on windows?

**Comment by shalabhaggarwal** [comment] 2013-08-05 08:33
This module does not depend on any Operating system.
Its just that windows natively does not support python and you should setup python properly.

You can refer to documentations and instructions online. Eg: http://docs.python.org/2/using/windows.html

Alternatively, you can hire some company for this purpose.

**Comment by stevelicu** [comment] 2013-08-05 08:55
Ok i added site-packages to the path and now i'm back to another error i allready had being 
Server Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\service\web_services.py", line 626, in dispatch
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 188, in execute_kw
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 131, in wrapper
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 197, in execute
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 185, in execute_cr
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\base\module\wizard\base_module_update.py", line 42, in update_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\base\module\module.py", line 617, in update_list
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\web\http.py", line 580, in load_addons
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\magento_.py", line 19, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\api.py", line 10, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\api.py", line 10, in <module>
ImportError: cannot import name API

**Comment by stevelicu** [comment] 2013-08-05 09:15
Ok i got trough the update of the update module list but and i installed the latest delivery module but when installing the integration i get Server Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\service\web_services.py", line 626, in dispatch
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 188, in execute_kw
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 131, in wrapper
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 197, in execute
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 185, in execute_cr
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\base\module\module.py", line 424, in button_immediate_install
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\base\module\module.py", line 475, in _button_immediate_function
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\pooler.py", line 39, in restart_pool
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\registry.py", line 218, in new
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\loading.py", line 345, in load_modules
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\loading.py", line 256, in load_marked_modules
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\loading.py", line 159, in load_module_graph
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 405, in load_openerp_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\delivery__init__.py", line 23, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\delivery\partner.py", line 24, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\delivery\partner.py", line 31, in res_partner
TypeError: **init**() takes exactly 2 non-keyword arguments (1 given)

can you point me to the correct delivery cost module

**Comment by shalabhaggarwal** [comment] 2013-08-05 09:30
@stevelicu We dont use any module apart from the ones already in the openerp standard addons.

**Comment by stevelicu** [comment] 2013-08-05 09:37
because the dependecies are   

delivery Te installeren 
base Geïnstalleerd 
mrp Te installeren 
sale Geïnstalleerd 

I adde delivery

**Comment by shalabhaggarwal** [comment] 2013-08-05 10:59
@stevelicu delivery is a part of standard addons for openerp. No need to add from outside.

You can cross check and confirm here http://bazaar.launchpad.net/~openerp/openobject-addons/7.0/files

**Comment by stevelicu** [comment] 2013-08-05 20:25
Hello thanks for the further help.
I have succesfully added the mrp and delivery components but i'm still suck with the magento integration itself.

First i tried to just put the files in the addon directory in the folder magento_integration, when i update the list it says cannot find module magento.
When i rename Magento integration to magento and i update i get 
Server Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\netsvc.py", line 292, in dispatch_rpc
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\service\web_services.py", line 626, in dispatch
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 188, in execute_kw
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 131, in wrapper
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 197, in execute
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\osv\osv.py", line 185, in execute_cr
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\base\module\wizard\base_module_update.py", line 42, in update_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\base\module\module.py", line 617, in update_list
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\web\http.py", line 580, in load_addons
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento__init__.py", line 9, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\magento_.py", line 17, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento__init__.py", line 11, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\product.py", line 8, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento__init__.py", line 12, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\partner.py", line 10, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento__init__.py", line 14, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\sale.py", line 12, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento__init__.py", line 17, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\wizard__init__.py", line 10, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\wizard\import_websites.py", line 11, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\api.py", line 10, in <module>
  File "C:\Program Files (x86)\OpenERP 7.0-20130728-231025\Server\server\openerp\addons\magento\api.py", line 10, in <module>
ImportError: cannot import name API

thanks again for the help

**Comment by mikea888** [comment] 2013-08-06 10:21
Problem seems to be that Openerp is not a native port in Windows. My suggestion would be to grab a VMware Player from   http://www.vmware.com/download/player/download.html and download the Opernerp vmware stack  from Bitnami http://bitnami.com/stack/openerp.

**Comment by shalabhaggarwal** [comment] 2013-08-06 10:44
@stevelicu You should NOT rename the module `magento_integration` to anything else. Please follow all the instructions as defined here https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation

**Comment by stevelicu** [comment] 2013-08-06 10:57
When i follow the instructions and i don t rename i get no module magento found

-----Oorspronkelijk bericht-----
Van: "Shalabh Aggarwal" notifications@github.com
Verzonden: ‎6/‎08/‎2013 12:44
Aan: "openlabs/magento_integration" magento_integration@noreply.github.com
CC: "stevelicu" steve@licu.be
Onderwerp: Re: [magento_integration] maximum recursion depth exceeded in cmp(#99)

@stevelicu You should NOT rename the module magento_integration to anything else. Please follow all the instructions as defined here https://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation

**Comment by shalabhaggarwal** [comment] 2013-08-06 11:00
@stevelicu You should install this https://github.com/openlabs/magento 
This a python module which is a dependency of the openerp module.

Ideally it should be installed automatically when you do `python setup.py install` but I am not sure why it does not get installed. Maybe due to windows being the OS.

**Comment by shalabhaggarwal** [comment] 2013-08-17 07:45
Closing this issue as there has no been no activity for a long time.

Feel free to reopen if needed.

**Closed as completed by shalabhaggarwal** 2013-08-17 07:45 UTC
Labels: duplicate

**Comment by stevelicu** [comment] 2013-08-19 17:48
Yep, sorry is work a while to get everything running in ubuntu but it is working now, so it looks like the module is not supported when running openerp on windows.
Thanks for the help doh.
