### ISSUE TITLE
Installation on Windows 7

### ISSUE THREAD

**Issue by Wessiez** [openlabs/magento_integration#133] opened 2013-10-04 13:21 UTC
Goodday,

I'm trying to install the connector on my windows 7 machine for testing the combination magento-openerp.
On the magento site everything goed well.
On the Openerp site I get all kinds of errors.

ImportError: No module named magento
ImportError: cannot import name API
or even can't login because it says: XmlHttpRequestError on a blank screen.

Is there anybody out there that got the connector working on a windows
machine with the versions OpenERP7 and Magento 1.7?
If so: How did you do it?

Best regards,
Wes

**Comment by sharoonthomas** [comment] 2013-10-04 14:00
Duplicate of #122

**Closed as completed by sharoonthomas** 2013-10-04 14:00 UTC
