### ISSUE TITLE
OpenERP Server Error. ImportError: No module named api

### ISSUE THREAD

**Issue by iamniels** [openlabs/magento_integration#120] opened 2013-09-05 14:59 UTC
I put the Magento module in the OpenERP folder and have run the `setup.py` installation. When I try to install the module from OpenERP now, I get the following error:

```
ImportError: No module named api
```

The full traceback is listed below. The Magento package from https://pypi.python.org/pypi/magento is installed.

Full traceback:

```
Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)


Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.6/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.6/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/pymodules/python2.6/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/pymodules/python2.6/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/usr/lib/pymodules/python2.6/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/pymodules/python2.6/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/usr/lib/pymodules/python2.6/openerp/addons/base/module/wizard/base_module_update.py", line 42, in update_module
    update, add = module_obj.update_list(cr, uid,)
  File "/usr/lib/pymodules/python2.6/openerp/addons/base/module/module.py", line 617, in update_list
    handler.load_addons()
  File "/usr/lib/pymodules/python2.6/openerp/addons/web/http.py", line 580, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/usr/lib/pymodules/python2.6/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/pymodules/python2.6/openerp/addons/magento_integration/__init__.py", line 9, in <module>
    import magento_
  File "/usr/lib/pymodules/python2.6/openerp/addons/magento_integration/magento_.py", line 19, in <module>
    from .api import OrderConfig
  File "/usr/lib/pymodules/python2.6/openerp/addons/magento_integration/api.py", line 10, in <module>
    from magento.api import API
ImportError: No module named api
```

**Comment by KevEd** [comment] 2013-09-07 19:36
Hi, I have same set-up, similar error when clicking the 'import website' button. Could someone advise whether this error message points to in incorrectly set up Magento store, or user/role in Magento or is it on the Openerp install server's setup?

Magento 1.7 has different choices for types of roles to set up SOAP/XML or REST or REST Oauth - which would be correct for this module? (The module does say 'connection successful' using the SOAP/XML option)

---

OpenERP Server Error
Client Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/python2.6/site-packages/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/python2.6/site-packages/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/python2.6/site-packages/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/python2.6/site-packages/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/python2.6/site-packages/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/python2.6/site-packages/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 91, in import_websites
    return self.open_websites(cursor, user, ids, instance, context)
  File "/usr/lib/python2.6/site-packages/openerp/addons/magento_integration-develop/wizard/import_websites.py", line 107, in open_websites
    cursor, user, 'magento_integration', 'instance_website_tree_view'
  File "/usr/lib/python2.6/site-packages/openerp/tools/cache.py", line 18, in lookup
    r = self.lookup(self2, cr, *args)
  File "/usr/lib/python2.6/site-packages/openerp/tools/cache.py", line 46, in lookup
    value = d[key] = self.method(self2, cr, *args)
  File "/usr/lib/python2.6/site-packages/openerp/addons/base/ir/ir_model.py", line 868, in get_object_reference
    data_id = self._get_id(cr, uid, module, xml_id)
  File "/usr/lib/python2.6/site-packages/openerp/tools/cache.py", line 18, in lookup
    r = self.lookup(self2, cr, *args)
  File "/usr/lib/python2.6/site-packages/openerp/tools/cache.py", line 46, in lookup
    value = d[key] = self.method(self2, cr, *args)
  File "/usr/lib/python2.6/site-packages/openerp/addons/base/ir/ir_model.py", line 861, in _get_id
    raise ValueError('No such external ID currently defined in the system: %s.%s' % (module, xml_id))
ValueError: No such external ID currently defined in the system: magento_integration.instance_website_tree_view

**Comment by dennisvandenende** [comment] 2013-09-11 11:48
i find a simulair problem as iamniels
I used "git clone git@github.com:openlabs/magento_integration.git"
 within the "addons" directory and started "python setup.py install" afterwards
result: Finished processing dependencies for magento-integration==0.1

but on "Update module list" within openerp:
this is the result:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/module/wizard/base_module_update.py", line 42, in update_module
    update, add = module_obj.update_list(cr, uid,)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/module/module.py", line 617, in update_list
    handler.load_addons()
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/**init**.py", line 9, in <module>
    import magento_
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/magento_.py", line 17, in <module>
    import magento
ImportError: No module named magento

**Comment by dennisvandenende** [comment] 2013-09-11 12:13
i installed addon magento from here explained by Levii Smith:
http://help.openerp.com/question/25650/importerror-no-module-named-pycountry/

but now i have this:
Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/module/wizard/base_module_update.py", line 42, in update_module
    update, add = module_obj.update_list(cr, uid,)
  File "/usr/lib/pymodules/python2.7/openerp/addons/base/module/module.py", line 617, in update_list
    handler.load_addons()
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 580, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/**init**.py", line 9, in <module>
    import magento_
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento_integration/magento_.py", line 17, in <module>
    import magento
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento/**init**.py", line 19, in <module>
    from .api import API
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento/api.py", line 27, in <module>
    from magento.utils import expand_url
  File "/usr/lib/pymodules/python2.7/openerp/modules/module.py", line 133, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/pymodules/python2.7/openerp/addons/magento/**init**.py", line 19, in <module>
    from .api import API
ImportError: cannot import name API

**Comment by dennisvandenende** [comment] 2013-09-11 13:28
it makes me crazy, i doesn't seem to find the problem.
I have "Welcome to Ubuntu 12.04.2 LTS (GNU/Linux 3.2.0-44-generic x86_64)"
clean openerp 7 installation just crm installed and that's it.
First thing i wanted to do is install magento connection.
this is as far as i get: ImportError: cannot import name API

Any suggestions?

**Comment by KevEd** [comment] 2013-09-11 14:01
Hi Dennis,
I've contacted the OpenLabs developer asking for a solution (paid or free)
to the python errors. The guys at UnitedHosting.co.uk have been doing a
brilliant job, installing and re-installing this module on different Ubuntu
server/php configurations and it still comes up with errors.
They got as far as the module showing up in the OpenERP apps list,
installing from there, the connection test succeeds but the Magento site
will not import into OpenERP. The shipping methods will import, so it's
partially working.

**Comment by KevEd** [comment] 2013-09-11 14:03
Having re-read your problem, I fixed that error by choosing the SOAP/XML
option for users and roles in magento.
Also check whether your site url is correct http://www.yoursite.com/  if
you have it hidden in a test directory or with an htaccess rule, the APi
won't connect.

**Comment by dennisvandenende** [comment] 2013-09-12 05:59
Hi KevEd,

my error exists on "Update Module List"
Even before i can configurate the Magento module.
I am desperate, because i just did the basic installations.

First i thought it must be the ownership of the directory structure on ubuntu. But i read it is okay that all files are owned by root:root. So this is not the problem.

I also checked if some file is corrupt, but also this is not so.
Then i checked if the error: from .api import API has something to do with a class he cannot find. But it should be found.

argh...

**Comment by KevEd** [comment] 2013-09-12 08:43
Hi Dennis,
If I were you I'd contact the techs at unitedhosting.co.uk they helped me
get past the problem stage you're at now, but there are further problems
which we cannot resolve. I contacted the developer who says, they'll fix it
for $400 (I'm not able to justify that expense).
Have you tried any alternative Magento/OpenERP integrations?

**Comment by dennisvandenende** [comment] 2013-09-12 08:51
Its odd, because i see other who can get past this error.
i am willing to pay for help, but this is still beta, so i am counting on the community in order to discuss the problems and improve the software bit by bit.

**Comment by sharoonthomas** [comment] 2013-09-12 08:57
Hello guys,

I work at Openlabs and the issue you are talking about is clearly an installation issue. The installation process [1] is well documented and you should follow it step by step (from step 2).

You must first install the python module for the api using `pip install magento` or `easy_install magento`.

And then you can place the module in the addons path with the folder name `magento_integration`. This is all what is required. Remember to restart openerp server depending on how it is installed.

From some of your stack traces I see that you are installing openerp to the root system python installation. You should use virtualenv.

In addition this is clearly **not** a problem with the connector or code, but your installation problem since the test suite [2] runs for every single commit building the whole thing (including downloading openerp) from scratch on a new virtual machine.

[1] http://openerp-magento-connector.readthedocs.org/en/develop/introduction.html#installation
[2] https://travis-ci.org/openlabs/magento-integration

**Comment by dennisvandenende** [comment] 2013-09-12 09:18
dear sharoonthomas

thanks for taking time. You solved my issue

This is the solution:
"You must first install the python module for the api using pip install magento or easy_install magento."
This should or can be part of the installion guide.

About the virtualenv i must say, that i installed by "apt-get openerp install" and this was the result i get.
But you are right, i will move it to a virtual env.

Thank again, and hopefully some others have help from this...

**Comment by sharoonthomas** [comment] 2013-09-12 09:56
@dennisvandenende 

I am glad it solved the problem. I am closing the ticket.

**Closed as completed by sharoonthomas** 2013-09-12 09:56 UTC

**Comment by iamniels** [comment] 2013-09-16 11:22
Thanks @sharoonthomas

**Comment by Wessiez** [comment] 2013-09-25 12:19
@sharoonthomas,

I installed the module exactly as you mentioned. I even installed the python module for api first, but no luck.
The problem is that when I'm trying to login OpenERP7 I get the "no handler found" error. When I remove the "magento_integration folder, I can login again.

Any Idea what it could be? I'm working with: Windows 7, python27, openERP 7.0

Greetings,
Wessiez

**Comment by pradeepnew** [comment] 2013-10-21 13:39
I followed the above steps magento_integration Module Installation issues is fixed. Currently able to Import or Export Product, Order details. But there is no option Customer Details Import or Export. And In the magento_integration module download partner_view.xml file is missing. Is any code available for Import or Export customer details.

**Comment by medyOne** [comment] 2015-05-24 02:38
please help i got this error when a want to integrate magento with openerp 

Traceback (most recent call last):

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\netsvc.py", line 300, in dispatch_rpc

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\service\web_services.py", line 632, in dispatch

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\osv\osv.py", line 190, in execute_kw

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\osv\osv.py", line 132, in wrapper

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\osv\osv.py", line 199, in execute

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\osv\osv.py", line 187, in execute_cr

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server\openerp\addons\base\module\module.py", line 684, in install_from_urls

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server\openerp\addons\base\module\module.py", line 616, in update_list

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server\openerp\addons\web\http.py", line 580, in load_addons

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server.\openerp\modules\module.py", line 133, in load_module

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server\openerp\addons\magento_integration__init__.py", line 9, in <module>

File "C:\Program Files (x86)\OpenERP 7.0-20150510\server\openerp\addons\magento_integration\magento_.py", line 17, in <module>

ImportError: No module named magento

2015-05-24 01:58:06,493 5008 INFO magento werkzeug: 127.0.0.1 - - [24/May/2015 01:58:06] "POST /web/dataset/call_button HTTP/1.1" 200 -

**Comment by sharoonthomas** [comment] 2015-05-24 04:50
You must have the magneto Python module installed which this module depends on. You can find the package on pypi. The source code is on GitHub too.
