### ISSUE TITLE
Import Catalog Error

### ISSUE THREAD

**Issue by jersobh** [openlabs/magento_integration#104] opened 2013-08-13 14:22 UTC
I get this error when i try to import catalog:

OpenERP

OpenERP Server Error

Client Traceback (most recent call last):
  File "/opt/openerp/7.0/web/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/openerp/7.0/web/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/openerp/7.0/web/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/openerp/7.0/web/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/7.0/web/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/7.0/web/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/7.0/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/7.0/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/7.0/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/7.0/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/7.0/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/7.0/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/7.0/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/7.0/addons/magento_integration/wizard/import_catalog.py", line 36, in import_catalog
    product_ids = self.import_products(cursor, user, website, context)
  File "/opt/openerp/7.0/addons/magento_integration/wizard/import_catalog.py", line 93, in import_products
    store_view=website.stores[0].store_views[0].magento_id
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/catalog.py", line 253, in list
    return self.call('catalog_product.list', [filters, store_view])
  File "/usr/local/lib/python2.7/dist-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: junk after document element: line 2, column 0

**Comment by shalabhaggarwal** [comment] 2013-08-14 05:53
Duplicate of #90

**Comment by lukebranch** [comment] 2013-08-20 05:42
I was having a similar issue and found the cause to be the following:

> > magento_integration directory was added to my addons directory as magento_integration-develop from the git download. Needed to change it to magento_integration  .
> > 
> > I have Nginx and Varnish serving my Magento shop. Varnish was trying to cache XML RPC requests from Openerp 7 which was causing an error message. I tested this on an identical instance of magento without Nginx and Varnish serving my Magento store and the connector worked without any issues.

Unfortunately Magento can be a little slow and Varnish/Nginx seems to be the best solution for speeding it up so i'll need to either setup a mirror of the magento instance running on localhost, or find a way to solve the Varnish / XML RPC issue that is causing the error.

If anyone has any insight to how this might be achieved with this module on either the Magento instance or the OpenERP 7 instance it would be much appreciated, as i'm sure I am not the only one running my Magento instance with this type of setup.

**Closed as completed** 2014-02-09 11:33 UTC
Labels: duplicate
