### ISSUE TITLE
Magento 1.9 Odoo v8/OpenERP v8

### ISSUE THREAD

**Issue by lukebranch** [openlabs/magento_integration#222] opened 2014-05-24 05:25 UTC
Hi,

I'd like to know if there are any plans to release an update to this module for compatibility with OpenERP v8/Odoo v8 (stable released early next month). I think there will be a huge demand for this given the current lack of a mature e-commerce module for Odoo v8/OpenERP v8, as the functionality is lacking for most e-commmerce users at this point in time.

Has anyone tested this module with Odoo v8/OpenERP v8:

https://github.com/odoo/odoo

**Comment by sharoonthomas** [comment] 2014-05-24 10:23
We (as authors) haven't yet tested this with OpenERP v8 and we will be doing it only when we will have a project on this version. And since Openlabs does not encourage its customers to move to v8/odoo this will have to wait.

However, patches (with  tests) are welcome.

**Comment by sharoonthomas** [comment] 2014-05-24 10:24
Duplicate of #221

**Closed as completed by sharoonthomas** 2014-05-24 10:24 UTC
