### ISSUE TITLE
Import Catalog Error

### ISSUE THREAD

**Issue by mikea888** [openlabs/magento_integration#90] opened 2013-07-25 08:00 UTC
Import catalog gives the following error:

OpenERP Server Error
Client Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1133, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/controllers/main.py", line 1121, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 43, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 31, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 104, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/web/session.py", line 90, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/netsvc.py", line 293, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration/wizard/import_catalog.py", line 37, in import_catalog
    product_ids = self.import_products(cursor, user, website, context)
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration/wizard/import_catalog.py", line 103, in import_products
    cursor, user, mag_product['product_id'], context,
  File "/opt/bitnami/apps/openerp/lib/openerp-7.0_20130508_231028-py2.7.egg/openerp/addons/magento_integration/product.py", line 255, in find_or_create_using_magento_id
    product_data = product_api.info(magento_id)
  File "/opt/bitnami/python/lib/python2.7/site-packages/magento-0.4-py2.7.egg/magento/catalog.py", line 265, in info
    'catalog_product.info', [product, store_view, attributes]
  File "/opt/bitnami/python/lib/python2.7/site-packages/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/opt/bitnami/python/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 7, column 10
Ok

**Comment by shalabhaggarwal** [comment] 2013-07-26 06:48
Hi @mikea888 

Seems like magento sends a response (most probably an error response) which is not a well formed XML.

Debugging this issue would require a lot more information and maybe a first hand access to the system.

**Comment by sharoonthomas** [comment] 2013-07-26 06:50
You could probably get more information if you look into magento (or your webserver) logs

**Comment by parthivgls** [comment] 2013-07-26 07:09
seems like duplicate of #89

**Comment by shalabhaggarwal** [comment] 2013-08-17 07:43
@mikea888 Any update on this issue?

If not, we can close this and reopen/report a new one if needed.

**Closed as completed** 2013-09-16 03:40 UTC

**Comment by tschonen** [comment] 2013-11-04 23:44
Hi @mikea888 

Did you manage t resolve this issue - I have the exact same config and problem?
Tom
